# Site settings
title: eomdev's blog
email: umsh86@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  배움을 좋아하고, 많고 다양한 경험을 해보기를 원합니다.

url: "https://blog.eomdev.com" # the base hostname & protocol for your site
github_username:  umsh86

# Build settings

# Configuring Jekyll
highlighter: rouge
#permalink: none
lsi: false


# paging
plugins:
  - jekyll-paginate
  - jemoji

paginate: 10          # 페이지당 글 수
paginate_path: "/page:num"  # /page2, /page3 ...
